# Generated by Django 6.0.5 on 2026-05-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(default='Available', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('author_wikipedia', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
